// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . f f 4 4 f f . . . . . 
. . . . f 5 4 5 5 4 5 f . . . . 
. . . f e 4 5 5 5 5 4 e f . . . 
. . f b 9 e 4 4 4 4 e 9 b f . . 
. . f 9 9 9 9 9 9 9 9 9 9 f . . 
. f 9 9 e b 9 e e 9 b e 9 9 f . 
. f 9 9 f f e e e e f f 9 9 f . 
. f b b f b f e e f b f b b f . 
. f b b e 1 f 4 4 f 1 e b b f . 
f f b b f 4 4 4 4 4 4 f b b f f 
f b b f f f e e e e f f f b b f 
. f e e f b d d d d b f e e f . 
. . e 4 c d d d d d d c 4 e . . 
. . e f b d b d b d b b f e . . 
. . . f f 1 d 1 d 1 d f f . . . 
. . . . . f f b b f f . . . . . 
`, img`
. . . . . . . f f . . . . . . . 
. . . . . f f 4 4 f f . . . . . 
. . . . f 5 4 5 5 4 5 f . . . . 
. . . f e 4 5 5 5 5 4 e f . . . 
. . f b 9 e 4 4 4 4 e 9 b f . . 
. f e 9 9 9 9 9 9 9 9 9 9 e f . 
. f 9 9 e b 9 e e 9 b e 9 9 f . 
. f b 9 f f e e e e f f 9 b f . 
f f b b f b f e e f b f b b f f 
f b b b e 1 f 4 4 f 1 e b b b f 
. f b b e e 4 4 4 4 4 f b b f . 
. . f 4 4 4 e d d d b f e f . . 
. . f e 4 4 e d d d d c 4 e . . 
. . . f e e d d b d b b f e . . 
. . . f f 1 d 1 d 1 1 f f . . . 
. . . . . f f f b b f . . . . . 
`, img`
. . . . . f f 4 4 f f . . . . . 
. . . . f 5 4 5 5 4 5 f . . . . 
. . . f e 4 5 5 5 5 4 e f . . . 
. . f b 9 e 4 4 4 4 e 9 b f . . 
. . f 9 9 9 9 9 9 9 9 9 9 f . . 
. f 9 9 e b 9 e e 9 b e 9 9 f . 
. f 9 9 f f e e e e f f 9 9 f . 
. f b b f b f e e f b f b b f . 
. f b b e 1 f 4 4 f 1 e b b f . 
f f b b f 4 4 4 4 4 4 f b b f f 
f b b f f f e e e e f f f b b f 
. f e e f b d d d d b f e e f . 
. . e 4 c d d d d d d c 4 e . . 
. . e f b d b d b d b b f e . . 
. . . f f 1 d 1 d 1 d f f . . . 
. . . . . f f b b f f . . . . . 
`, img`
. . . . . . . f f . . . . . . . 
. . . . . f f 4 4 f f . . . . . 
. . . . f 5 4 5 5 4 5 f . . . . 
. . . f e 4 5 5 5 5 4 e f . . . 
. . f b 9 e 4 4 4 4 e 9 b f . . 
. f e 9 9 9 9 9 9 9 9 9 9 e f . 
. f 9 9 e b 9 e e 9 b e 9 9 f . 
. f b 9 f f e e e e f f 9 b f . 
f f b b f b f e e f b f b b f f 
f b b b e 1 f 4 4 f 1 e b b b f 
. f b b f 4 4 4 4 4 e e b b f . 
. . f e f b d d d e 4 4 4 f . . 
. . e 4 c d d d d e 4 4 e f . . 
. . e f b b d b d d e e f . . . 
. . . f f 1 1 d 1 d 1 f f . . . 
. . . . . f b b f f f . . . . . 
`];
            case "myAnim0":
            case "anim2":return [img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.......fbddddddbf.......
......fffc3bdb3ffff.....
....fcdddcbfbfcdddcf....
....fdbdbdffffdbdbdf....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.......fbddddddffff.....
......fffc3bdbcdddcf....
....fcdddcbfbfdbdbdf....
....fdbdbdffffbfbfbf....
....fbfbfffffff.........
.........fffff..........
..........fff...........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.......fbddddddbf.......
......fffc3bdb3ffff.....
....fcdddcbfbfcdddcf....
....fdbdbdffffdbdbdf....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.....ffffddddddbf.......
....fcdddc3bdb3fff......
....fdbdbcbfbfcdddcf....
....fbfbfbffffdbdbdf....
.........fffffffbfbf....
..........fffff.........
...........fff..........
........................
........................
........................
........................
`];
            case "real":
            case "anim3":return [img`
........................
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.....fffcdddddddf.......
...fcdddc3dddddddf......
...fdbdbdbdddd333f......
...fbfbffcfddfc33f......
......fcfddddddbbf......
.......ccb3bdbdfcf......
.......fffbfbf3ff.......
........ffffffff........
........fffffffffff.....
.........fffffcdddcf....
.........fffffdbdbdf....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
....9.f3dddddddd3f......
...9..f3dddddddd3f......
...9..f3dddddddd3f......
...9..f333dddd333ff.....
...99.fb3bf33fb3bfcf....
...999fc3cfddfc3cfbf....
....99fffb3bdb3ffcf.....
....fcbdbcffffff........
....fdcdcdffffff........
....f3f3f3fffff.........
.....f.f.f..............
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddddf......
......f3dddddddd3f......
......f3dddddddd3f......
......fc33dddd33cff.....
.......fbcfddfcbfbbf....
.......ffb3bdb3ffff.....
........fcbfbf3f........
........ffffffff........
......ffffffffff........
.....fcbdbcffff.........
......ffbff.............
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f33dddddd33f......
......fb33dddd333f......
......fc3bf33fb3bf......
.......fbcfddfcbfff.....
.......ffbddddbcfbcf....
........fc3bdb3fbbbf....
.......ffffffffffcf.....
.....fcbdbcfffff........
.....fdbdbdffff.........
......ffbff.............
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
