// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim0":
            case "anim2":return [img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.......fbddddddbf.......
......fffc3bdb3ffff.....
....fcdddcbfbfcdddcf....
....fdbdbdffffdbdbdf....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.......fbddddddffff.....
......fffc3bdbcdddcf....
....fcdddcbfbfdbdbdf....
....fdbdbdffffbfbfbf....
....fbfbfffffff.........
.........fffff..........
..........fff...........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.......fbddddddbf.......
......fffc3bdb3ffff.....
....fcdddcbfbfcdddcf....
....fdbdbdffffdbdbdf....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ffddddff........
.......fbddddddbf.......
.......fddddddddf.......
......f3dddddddd3f......
......f3dddddddd3f......
......f333dddd333f......
......fb3bf33fb3bf......
......fc3cfddfc3cf......
.....ffffddddddbf.......
....fcdddc3bdb3fff......
....fdbdbcbfbfcdddcf....
....fbfbfbffffdbdbdf....
.........fffffffbfbf....
..........fffff.........
...........fff..........
........................
........................
........................
........................
`];
            case "myAnim":
            case "anim1":return [img`
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f f f f 9 f f f . . 
f f f f f f 9 9 f f f 9 . 
f f f 9 f f f f f f f 9 . 
9 9 9 f f f d d f f 9 9 . 
f f f f f d d f f 9 9 f . 
f f f b f d d f b f f f . 
. f 1 2 f 1 1 f 2 1 f . . 
. f d 1 1 1 1 1 1 d f . . 
. f f f d d d d f f f . . 
f d f b 8 8 8 8 b f d f . 
d 1 f 8 8 8 8 8 8 f 4 d . 
d d f 6 6 6 6 6 6 f d d . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . . f f f f . . . . 
. . . f f f f f f f f . . 
. . f f f f f f 9 f f f . 
f f f f f f f 9 9 f f f 9 
f f f f 9 f f f f f f f 9 
. 9 9 9 f f f d d f f 9 9 
. f f f f f d d f f 9 9 f 
. f f f b f d d f b f f f 
. f f 1 2 f 1 1 f 2 1 f f 
. . f 1 1 1 1 1 1 d d f d 
. f d d b 8 8 8 d 1 1 1 d 
. d 1 f 8 8 8 8 d 1 1 d . 
. . . f 6 6 6 6 6 d d . . 
. . . f f f f f f f . . . 
. . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . 
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f 9 f f f f f f . . 
9 f f f 9 9 f f f f f f f 
9 f f f f f f f 9 f f f f 
9 9 f f d d f f f 9 9 9 . 
f 9 9 f f d d f f f f f . 
f f f b f d d f b f f f . 
f f 1 2 f 1 1 f 2 1 f f . 
d f d d 1 1 1 1 1 d f . . 
d 1 1 1 d 8 8 8 b f d f . 
. d 1 1 d 8 8 8 8 f 1 d . 
. . d d 6 6 6 6 6 f . . . 
. . . f f f f f f f . . . 
. . . . . . . f f f . . . 
`];
            case "real":
            case "anim3":return [img`
. . 4 4 4 . . . . 4 4 4 . . . . 
. 4 5 5 5 e . . e 5 5 5 4 . . . 
4 5 5 5 5 5 e e 5 5 5 5 5 4 . . 
4 5 5 4 4 5 5 5 5 4 4 5 5 4 . . 
e 5 4 4 5 5 5 5 5 5 4 4 5 e . . 
. e e 5 5 5 5 5 5 5 5 e e . . . 
. . e 5 f 5 5 5 5 f 5 e . . . . 
. . f 5 5 5 4 4 5 5 5 f . . f f 
. . f 4 5 5 f f 5 5 6 f . f 5 f 
. . . f 6 6 6 6 6 6 4 4 f 5 5 f 
. . . f 4 5 5 5 5 5 5 4 4 5 f . 
. . . f 5 5 5 5 5 4 5 5 f f . . 
. . . f 5 f f f 5 f f 5 f . . . 
. . . f f . . f f . . f f . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 4 4 . . . . 4 4 4 . . . . 
. 4 5 5 5 e . . e 5 5 5 4 . . . 
4 5 5 5 5 5 e e 5 5 5 5 5 4 . . 
4 5 5 4 4 5 5 5 5 4 4 5 5 4 . . 
e 5 4 4 5 5 5 5 5 5 4 4 5 e . . 
. e e 5 5 5 5 5 5 5 5 e e . . . 
. . e 5 f 5 5 5 5 f 5 e . . . . 
. . f 5 5 5 4 4 5 5 5 f . f f . 
. . . 4 5 5 f f 5 5 6 f f 5 f . 
. . . f 6 6 6 6 6 6 4 4 4 5 f . 
. . . f 5 5 5 5 5 5 5 f f f . . 
. . . f 5 4 5 f f f 5 f . . . . 
. . . f f f f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 4 4 . . . . 4 4 4 . . . . 
. 4 5 5 5 e . . e 5 5 5 4 . . . 
4 5 5 5 5 5 e e 5 5 5 5 5 4 . . 
4 5 5 4 4 5 5 5 5 4 4 5 5 4 . . 
e 5 4 4 5 5 5 5 5 5 4 4 5 e . . 
. e e 5 5 5 5 5 5 5 5 e e . . . 
. . e 5 f 5 5 5 5 f 5 e . . . . 
. . f 5 5 5 4 4 5 5 5 f . f f . 
. . . 4 5 5 f f 5 5 6 f f 5 f . 
. . . f 6 6 6 6 6 6 4 f 5 5 f . 
. . . f 5 5 5 5 5 5 5 4 5 f . . 
. . . . f 5 4 5 f 5 f f f . . . 
. . . . . f f f f f f f . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
